-- Create the user (this IS your schema in Oracle)
CREATE USER auth_user IDENTIFIED BY YourStrongPassword123;

-- Grant necessary permissions
GRANT CONNECT TO auth_user;
GRANT RESOURCE TO auth_user;
GRANT CREATE SESSION TO auth_user;
GRANT UNLIMITED TABLESPACE TO auth_user;

CREATE TABLE USERS (
    USER_ID         VARCHAR2(36)        PRIMARY KEY,
    EMAIL           VARCHAR2(255)       NOT NULL UNIQUE,
    USERNAME        VARCHAR2(100)       UNIQUE,
    PASSWORD_HASH   VARCHAR2(255),
    PROVIDER        VARCHAR2(20)        DEFAULT 'LOCAL' NOT NULL
                    CHECK (PROVIDER IN ('LOCAL','GOOGLE','GITHUB','FACEBOOK','APPLE')),
    PROVIDER_ID     VARCHAR2(255),
    IS_VERIFIED     NUMBER(1)           DEFAULT 0 NOT NULL CHECK (IS_VERIFIED IN (0,1)),
    IS_ACTIVE       NUMBER(1)           DEFAULT 1 NOT NULL CHECK (IS_ACTIVE IN (0,1)),
    FAILED_LOGIN_ATTEMPTS VARCHAR2(10)  DEFAULT '0',
    LOCKED_UNTIL    TIMESTAMP WITH TIME ZONE,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ROLES (
    ROLE_ID     VARCHAR2(36)    PRIMARY KEY,
    ROLE_NAME   VARCHAR2(20)    NOT NULL UNIQUE
                CHECK (ROLE_NAME IN ('OWNER','ADMIN','DEVELOPER','VIEWER','AI_AGENT'))
);

CREATE TABLE USER_ROLES (
    USER_ID     VARCHAR2(36)    NOT NULL,
    ROLE_ID     VARCHAR2(36)    NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT fk_userroles_user FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT fk_userroles_role FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID) ON DELETE CASCADE
);

CREATE TABLE REFRESH_TOKENS (
    TOKEN_ID    VARCHAR2(36)                PRIMARY KEY,
    USER_ID     VARCHAR2(36)                NOT NULL,
    TOKEN       VARCHAR2(512)               NOT NULL UNIQUE,
    EXPIRES_AT  TIMESTAMP WITH TIME ZONE    NOT NULL,
    IS_REVOKED  NUMBER(1) DEFAULT 0         NOT NULL CHECK (IS_REVOKED IN (0,1)),
    CREATED_AT  TIMESTAMP WITH TIME ZONE    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_refreshtoken_user FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- Speed up email lookups (login)
CREATE INDEX idx_users_email ON USERS(EMAIL);

-- Speed up token lookups
CREATE INDEX idx_refresh_tokens_user ON REFRESH_TOKENS(USER_ID);
CREATE INDEX idx_refresh_tokens_token ON REFRESH_TOKENS(TOKEN);

-- Speed up role lookups per user
CREATE INDEX idx_user_roles_user ON USER_ROLES(USER_ID);


INSERT INTO ROLES (ROLE_ID, ROLE_NAME) VALUES (SYS_GUID(), 'OWNER');
INSERT INTO ROLES (ROLE_ID, ROLE_NAME) VALUES (SYS_GUID(), 'ADMIN');
INSERT INTO ROLES (ROLE_ID, ROLE_NAME) VALUES (SYS_GUID(), 'DEVELOPER');
INSERT INTO ROLES (ROLE_ID, ROLE_NAME) VALUES (SYS_GUID(), 'VIEWER');
INSERT INTO ROLES (ROLE_ID, ROLE_NAME) VALUES (SYS_GUID(), 'AI_AGENT');

COMMIT;


-- Check roles were inserted
SELECT * FROM ROLES;

-- Check table structure
DESC USERS;
DESC ROLES;
DESC USER_ROLES;
DESC REFRESH_TOKENS;
